### PR TITLE
Add Laguerre RSI Indicator

### PR DESCRIPTION
**Pull request by rterbush**

### CODE REVIEW

**Comment by mementum** [comment]
Upon closer inspection, the accounting of the `l0 -> l3` values is easier than it seems and needs no array structure at all.

The calculation before the minimum period is met has also been added (is just the last term that gets canceled by means of a boolean)

Should the results diverge from the expected, please leave a notice.

**Comment by rterbush** [comment]
@mementum latest changes did change the output. Takes the resolution back to results I was battling a bit before. See graph:

image

**Comment by rterbush** [comment]
Here is graph posted last night when I got this working:
image

**Comment by mementum** [comment]
The original and the new will be compared. Thank you for double checking

**Comment by mementum** [comment]
There was a `11` typo instead of the needed `l1` and that was the reason for the incorrection.

The final implementation respects the original implementation by *Ehlers* and rather than expecting the price component to have `high` and `low` it takes simply `self.data` (which unless changed is the `close` from regular data feeds)

Using it for the midpoint of the bar is easy:

```python
midpoint = (self.data.high + self.data.low) / 2.0
lrsi = bt.ind.LRSI(midpoint)
```

The advantange of not having specifics like `high` and `low` in the code is that the `LRSI` can be calculated for anything which is a data feed or descendant of ... you could create the `LRSI` of a `SimpleMovingAverage`

**Pull request merged**
