### PR TITLE
Enable OCO for close orders

### PR DESCRIPTION
**Pull request by dimitar-petrov**

### CODE REVIEW

**Comment by mementum** [comment]
The development branch already does this (some unpushed changed though) simplifying the arguments.

**Comment by mementum** [comment]
All changes were pushed to the `development` branch

**Comment by dimitar-petrov** [comment]
Hi mementum,

For some reason oco is not getting to _ocoize:

`
> /home/dpetrov/develop/python/py-envs/py3env/lib/python3.6/site-packages/backtrader/brokers/bbroker.py(477)_ocoize()
-> oref = order.ref
(Pdb) args
self = <backtrader.brokers.bbroker.BackBroker object at 0x7f452301ef28>
order = <backtrader.order.SellOrder object at 0x7f4522d64dd8>
oco = None
(Pdb) bt
/usr/lib64/python3.6/bdb.py(431)run()
-> exec(cmd, globals, locals)
<string>(1)<module>()
/home/dpetrov/develop/python/stester/stester/stester.py(1174)<module>()
-> btrun(args=args)
/home/dpetrov/develop/python/stester/stester/stester.py(147)btrun()
-> runsts = cerebro.run()
/home/dpetrov/develop/python/py-envs/py3env/lib/python3.6/site-packages/backtrader/cerebro.py(794)run()
-> runstrat = self.runstrategies(iterstrat)
/home/dpetrov/develop/python/py-envs/py3env/lib/python3.6/site-packages/backtrader/cerebro.py(924)runstrategies()
-> self._runnext(runstrats)
/home/dpetrov/develop/python/py-envs/py3env/lib/python3.6/site-packages/backtrader/cerebro.py(1240)_runnext()
-> strat._next()
/home/dpetrov/develop/python/py-envs/py3env/lib/python3.6/site-packages/backtrader/strategy.py(296)_next()
-> super(Strategy, self)._next()
/home/dpetrov/develop/python/py-envs/py3env/lib/python3.6/site-packages/backtrader/lineiterator.py(245)_next()
-> self._notify()
/home/dpetrov/develop/python/py-envs/py3env/lib/python3.6/site-packages/backtrader/strategy.py(499)_notify()
-> self.notify_order(order)
/home/dpetrov/develop/python/stester/strats/FirstPivot/FirstPivot_A.py(182)notify_order()
-> oco=sl_ord)
/home/dpetrov/develop/python/py-envs/py3env/lib/python3.6/site-packages/backtrader/strategy.py(863)order_target_value()
-> tradeid=tradeid, **kwargs)
/home/dpetrov/develop/python/py-envs/py3env/lib/python3.6/site-packages/backtrader/strategy.py(762)close()
-> **kwargs)
/home/dpetrov/develop/python/py-envs/py3env/lib/python3.6/site-packages/backtrader/strategy.py(730)sell()
-> **kwargs)
/home/dpetrov/develop/python/py-envs/py3env/lib/python3.6/site-packages/backtrader/brokers/bbroker.py(514)sell()
-> self._ocoize(order, oco)
> /home/dpetrov/develop/python/py-envs/py3env/lib/python3.6/site-packages/backtrader/brokers/bbroker.py(477)_ocoize()
-> oref = order.ref
(Pdb) u
> /home/dpetrov/develop/python/py-envs/py3env/lib/python3.6/site-packages/backtrader/brokers/bbroker.py(514)sell()
-> self._ocoize(order, oco)
(Pdb) u
> /home/dpetrov/develop/python/py-envs/py3env/lib/python3.6/site-packages/backtrader/strategy.py(730)sell()
-> **kwargs)
(Pdb) u
> /home/dpetrov/develop/python/py-envs/py3env/lib/python3.6/site-packages/backtrader/strategy.py(762)close()
-> **kwargs)
(Pdb) u
> /home/dpetrov/develop/python/py-envs/py3env/lib/python3.6/site-packages/backtrader/strategy.py(863)order_target_value()
-> tradeid=tradeid, **kwargs)
(Pdb) args
self = <QFFL8WWFUF.FirstPivot_A object at 0x7f4523011ef0>
data = <custfeeds.ResampledOHLCV object at 0x7f452301ee80>
target = 0
price = 927.9299999999998
plimit = None
exectype = 2
valid = None
tradeid = 0
oco = <backtrader.order.SellOrder object at 0x7f4522d64748>
trailamount = None
trailpercent = None
kwargs = {}
`
I am on the following commit:

git log | head -15
commit fa5542e3fa8b3e638792b610f70dfcd4970532f6
Author: Dimitar Petrov <finkata@gmail.com>
Date:   Sat Mar 25 22:23:05 2017 +0200

    Fix OCO child order cancel (#290)

commit 65ce53123df36b686a264bf38b46e5e8c8762427
Author: mementum <mementum@users.noreply.github.com>
Date:   Sat Mar 25 20:57:04 2017 +0100

    Update order_target_xxx for oco and stoptrails

commit 9de7b0f15520676ad1e666b004af31803243c307
Author: mementum <mementum@users.noreply.github.com>
Date:   Thu Mar 23 06:54:40 2017 +0100

BR,
Dimitar

**Comment by mementum** [comment]
That log seems utterly complex to decode. This is the sample to test `OCO` adapted to allow using `order_target_size`

```python
#!/usr/bin/env python
# -*- coding: utf-8; py-indent-offset:4 -*-
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)


import argparse
import datetime

import backtrader as bt


class St(bt.Strategy):
    params = dict(
        ma=bt.ind.SMA,
        p1=5,
        p2=15,
        limit=0.005,
        limdays=3,
        limdays2=1000,
        hold=10,
        usetarget=False,  # use order_target_size
        switchp1p2=False,  # switch prices of order1 and order2
        oco1oco2=False,  # False - use order1 as oco for order3, else order2
        do_oco=True,  # use oco or not
    )

    def notify_order(self, order):
        print('{}: Order ref: {} / Type {} / Status {}'.format(
            self.data.datetime.date(0),
            order.ref, 'Buy' * order.isbuy() or 'Sell',
            order.getstatusname()))

        if order.status == order.Completed:
            self.holdstart = len(self)

        if not order.alive() and order.ref in self.orefs:
            self.orefs.remove(order.ref)

    def __init__(self):
        ma1, ma2 = self.p.ma(period=self.p.p1), self.p.ma(period=self.p.p2)
        self.cross = bt.ind.CrossOver(ma1, ma2)

        self.orefs = list()

        if self.p.usetarget:
            print('-' * 5, 'Using order_target_size')
            self._dobuy = self.order_target_size
            self._doclose = self.order_target_size
        else:
            self._dobuy = self.buy
            self._doclose = self.close

    def next(self):
        if self.orefs:
            return  # pending orders do nothing

        if not self.position:
            if self.cross > 0.0:  # crossing up

                p1 = self.data.close[0] * (1.0 - self.p.limit)
                p2 = self.data.close[0] * (1.0 - 2 * 2 * self.p.limit)
                p3 = self.data.close[0] * (1.0 - 3 * 3 * self.p.limit)

                valid1 = datetime.timedelta(self.p.limdays)
                valid2 = valid3 = datetime.timedelta(self.p.limdays2)

                if self.p.switchp1p2:
                    p1, p2 = p2, p1
                    valid1, valid2 = valid2, valid1

                print('valid1 is:', valid1)

                kargs = dict(exectype=bt.Order.Limit)
                kargs[('target' * self.p.usetarget) or 'size'] = 1

                o1 = self._dobuy(price=p1, valid=valid1, **kargs)
                print('{}: Oref {} / Buy at {}'.format(
                    self.datetime.date(), o1.ref, p1))

                oco2 = o1 if self.p.do_oco else None
                o2 = self._dobuy(price=p2, valid=valid2, oco=oco2, **kargs)

                print('{}: Oref {} / Buy at {}'.format(
                    self.datetime.date(), o2.ref, p2))

                if self.p.do_oco:
                    oco3 = o1 if not self.p.oco1oco2 else oco2
                else:
                    oco3 = None

                o3 = self._dobuy(price=p3, valid=valid3, oco=oco3, **kargs)

                print('{}: Oref {} / Buy at {}'.format(
                    self.datetime.date(), o3.ref, p3))

                self.orefs = [o1.ref, o2.ref, o3.ref]

        else:  # in the market
            if (len(self) - self.holdstart) >= self.p.hold:
                self._doclose()


def runstrat(args=None):
    args = parse_args(args)

    cerebro = bt.Cerebro()

    # Data feed kwargs
    kwargs = dict()

    # Parse from/to-date
    dtfmt, tmfmt = '%Y-%m-%d', 'T%H:%M:%S'
    for a, d in ((getattr(args, x), x) for x in ['fromdate', 'todate']):
        if a:
            strpfmt = dtfmt + tmfmt * ('T' in a)
            kwargs[d] = datetime.datetime.strptime(a, strpfmt)

    # Data feed
    data0 = bt.feeds.BacktraderCSVData(dataname=args.data0, **kwargs)
    cerebro.adddata(data0)

    # Broker
    cerebro.broker = bt.brokers.BackBroker(**eval('dict(' + args.broker + ')'))

    # Sizer
    cerebro.addsizer(bt.sizers.FixedSize, **eval('dict(' + args.sizer + ')'))

    # Strategy
    cerebro.addstrategy(St, **eval('dict(' + args.strat + ')'))

    # Execute
    cerebro.run(**eval('dict(' + args.cerebro + ')'))

    if args.plot:  # Plot if requested to
        cerebro.plot(**eval('dict(' + args.plot + ')'))


def parse_args(pargs=None):
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description=(
            'Sample Skeleton'
        )
    )

    parser.add_argument('--data0', default='../../datas/2005-2006-day-001.txt',
                        required=False, help='Data to read in')

    # Defaults for dates
    parser.add_argument('--fromdate', required=False, default='',
                        help='Date[time] in YYYY-MM-DD[THH:MM:SS] format')

    parser.add_argument('--todate', required=False, default='',
                        help='Date[time] in YYYY-MM-DD[THH:MM:SS] format')

    parser.add_argument('--cerebro', required=False, default='',
                        metavar='kwargs', help='kwargs in key=value format')

    parser.add_argument('--broker', required=False, default='',
                        metavar='kwargs', help='kwargs in key=value format')

    parser.add_argument('--sizer', required=False, default='',
                        metavar='kwargs', help='kwargs in key=value format')

    parser.add_argument('--strat', required=False, default='',
                        metavar='kwargs', help='kwargs in key=value format')

    parser.add_argument('--plot', required=False, default='',
                        nargs='?', const='{}',
                        metavar='kwargs', help='kwargs in key=value format')

    return parser.parse_args(pargs)


if __name__ == '__main__':
    runstrat()
```

A sample execution switching the prices of *order1* and *order2* to make sure *order2* is the one that can eventually get executed and that *order1* (the 1st to be sent to the system and as such the *parent*) is canceled by the child.

```
$ ./oco.py --plot --broker cash=50000 --strat usetarget=True,switchp1p2=True
----- Using order_target_size
valid1 is: 1000 days, 0:00:00
2005-01-28: Oref 1 / Buy at 2896.7722
2005-01-28: Oref 2 / Buy at 2941.11055
2005-01-28: Oref 3 / Buy at 2822.87495
2005-01-31: Order ref: 1 / Type Buy / Status Submitted
2005-01-31: Order ref: 2 / Type Buy / Status Submitted
2005-01-31: Order ref: 3 / Type Buy / Status Submitted
2005-01-31: Order ref: 1 / Type Buy / Status Accepted
2005-01-31: Order ref: 2 / Type Buy / Status Accepted
2005-01-31: Order ref: 3 / Type Buy / Status Accepted
2005-02-01: Order ref: 2 / Type Buy / Status Expired
2005-02-01: Order ref: 1 / Type Buy / Status Canceled
2005-02-01: Order ref: 3 / Type Buy / Status Canceled
valid1 is: 1000 days, 0:00:00
2005-03-03: Oref 4 / Buy at 3016.5478
2005-03-03: Oref 5 / Buy at 3062.71945
2005-03-03: Oref 6 / Buy at 2939.59505
2005-03-04: Order ref: 4 / Type Buy / Status Submitted
2005-03-04: Order ref: 5 / Type Buy / Status Submitted
2005-03-04: Order ref: 6 / Type Buy / Status Submitted
2005-03-04: Order ref: 4 / Type Buy / Status Accepted
2005-03-04: Order ref: 5 / Type Buy / Status Accepted
2005-03-04: Order ref: 6 / Type Buy / Status Accepted
2005-03-07: Order ref: 5 / Type Buy / Status Expired
2005-03-07: Order ref: 4 / Type Buy / Status Canceled
2005-03-07: Order ref: 6 / Type Buy / Status Canceled
...
...
```

And the chart

image

If you set `switchp1p2` to `False` then `order1` will be executed (or expired) and `order2` will get canceled.

**Comment by mementum** [comment]
This of course with the latest commit that pushes all the changes to allow the arguments to go transparently (those not needed in `order_target_xxx` or elsewhere) down to `buy` and `sell`

**Pull request closed without merging**
