### PR TITLE
Yahoo 404 - Changed the request User-Agent to accepted value

### PR DESCRIPTION
**Pull request by frruit**
Without this change the simple basic tutorials are not executable because yahoo blocks the default user agent from the requests lib

### CODE REVIEW

**Comment by neilsmurphy** [comment]
@frruit  Updated backtrader 2 [PR#67](https://github.com/backtrader2/backtrader/pull/67)

**Comment by amarvin** [comment]
This PR fixes [the tutorial example](https://www.backtrader.com/home/helloalgotrading/), which is [currently broken](https://stackoverflow.com/q/60715059/6068036) limiting adoption by new users.

**Review by vladisld — APPROVED** [review]

**Review by vladisld — APPROVED** [review]

**Comment by mptnt1988** [comment]
May I ask when this will be released?

**Comment by neilsmurphy** [comment]
> May I ask when this will be released?

The creator of Backtrader no longer maintains the repo. Your changes are in `master`. You are probably best to clone and implement.

**Comment by mptnt1988** [comment]
> > May I ask when this will be released?
> 
> The creator of Backtrader no longer maintains the repo. Your changes are in `master`. You are probably best to clone and implement.

Thanks for your info

**Comment by amarvin** [comment]
> You are probably best to clone and implement.

You can also install from the latest source using `pip install git+https://github.com/mementum/backtrader.git#egg=backtrader`.

**Comment by Shadmeister** [comment]
Hi,
Yahoo with backtrader use to work for me as of 28th June 2021, but i did not test later. Since upgrading F33 to F34, it fails with File Not Found. 

Using pip i upgraded pip, yfinance (works on other scripts), and installed backtrader2, yet backtrader does not work. 

Backtrader version 1 was not removed when i installed backtrader2. 

I can see packets going to yahoo when i run the script. 

I tried to implement : `import backtrader2 as bt`
But the module is not recognised, so `backtrader` is used.

Since backtrader (updated to 1.9.76.123) was not removed, is there a conflict where backtrader2 is never invoked, and it is defaulting to backtrader version 1 ?

Thanks and regards,
Shadmeister.

**Comment by vladisld** [comment]
What is that backtrader2 pypi package? I don't remember we ever published anything from https://github.com/backtrader2/backtrader. It could be that someone republished the original backtrader package under backtrader2 name creating this confusion. It is unclear to me what fixes this package provides beyond the official backtrader package.

**Comment by brianhumphreys** [comment]
Hey all.  The support in this channel is much appreciated.  

I see the user-agent header addition has been merged but I am still receiving this issue.  Is this happening for anyone else?

**Comment by Shadmeister** [comment]
Hi,
The github corrected code has not been published to pypi website,. When you use pip to install packages such as backtrader, the pypi website is used to download the code. 

Someone has published backtrader2 to pypi, but this does not work, and i have yet to investigate whether it is a rogue code or trojan. 

As such, there is the instruction to instruct pip to use the github version in this thread upstream, so you will have to use that, or modify the relevant file as above. 

It would be good if the github code was published to pypi so people can use the corrected coded without having to search.

Regards,
Shadmeister.

**Comment by Shadmeister** [comment]
Hi,
Not sure how to address this, but backtrader2 has been published on pypi.org. 
https://pypi.org/project/backtrader2/
It references the backtrader version 1 links, yet it is unknown if the code is the same as backtrader version 1. 

Of a serious concern is the following :
https://thehackernews.com/2021/11/11-malicious-pypi-python-libraries.html

Although backtrader is not mentioned, if yourselves do not know who uploaded backtrader2 to the pypi.org repository, then is it possible that the code has a trojan or other installed ?

The backtrader2 on pypi.org references github repository which does now not exist, but using the pip installation command, still installs. 

So, how can this issue be progressed ?

Thanks and regards,
Shadmeister.

**Comment by iniself** [comment]
Don‘t install backtrader via pip.`git clone` this repo and then copy backtrader folder to your site-packages

**Comment by tengerye** [comment]
> Don‘t install backtrader via pip.`git clone` this repo and then copy backtrader folder to your site-packages

Same error for [the official example](https://www.backtrader.com/blog/posts/2016-04-19-sync-different-markets/sync-different-markets/).

**Comment by datatalking** [comment]
@iniself > Don‘t install backtrader via pip.`git clone` this repo and then copy backtrader folder to your site-packages

When you say `git clone` this repo, how do you keep track of updates, PATH issues, or do you have a dedicated `git clone` folder that all your files go into and you copy them out as needed?

**Pull request merged**
