### PR TITLE
Add DV2 indicator and fix up imports.

### PR DESCRIPTION
**Pull request by rterbush**

### CODE REVIEW

**Comment by mementum** [comment]
For consistency, with most other indicators, the `rperiod` parameter will be renamed to `period`. The moving average period will be made a parameter and the moving average type too.

It seems that `DV2` is a direct descendant, or even just a fixed parameter combination, of `DVO` also by Dave Varaldi. Getting both on board will be attempted.

**Comment by rterbush** [comment]
@mementum just for the record, I left the 2-period average hard coded since the DV**2**  (and that average setting) is one of the characteristics of this indicator, and left the "Ranking" period a parameter in case anyone wanted to use that knob. `rperiod` was my attempt to make it clearer that you weren't tuning the 2 period average.

But that said, perhaps someone will find it useful to turn this other knob.

**Comment by mementum** [comment]
Some extra literature: http://web.archive.org/web/20131216100741/http://quantingdutchman.wordpress.com/2010/08/06/dv2-indicator-for-amibroker/

The formula is the same one found there. It seems to be the "Bounded" version.

From Varaldi himself: https://cssanalytics.wordpress.com/2009/07/29/differential-dv2-calculation/

There the DV2 calculations don't take the average of High and Low ... which could mean it is the unbounded version, but there is an additional comment: *not the unbounded version*

**Comment by mementum** [comment]
And some code which seems to be for the generic `DVO` and in theory could also yield (with specific settings) the DV2

https://github.com/IlyaKipnis/IKTrading/blob/master/R/DVO.R

**Pull request merged**
