### PR TITLE
Fix: using abs() to void negative values in pow(meansq - sqmean, 0.5)

### PR DESCRIPTION
**Pull request by pblenessy**

### CODE REVIEW

**Comment by mementum** [comment]
The pull request is clear, but I fail to understand how you can have negative values.

Unless I happen to be very wrong, the sum of n squared values divided by n, should be always greater than the sum of the values divided by n and squared.

Example 1:

  - 2 + 5 = 7, average = 3.5, squared average 12.25
  - Summing the squares: `4 + 25 = 29` and dividing by N (2 in this case): `14.5`
  - Difference: `14.5 - 12.25 = 2.25`

If we change 2 or 5 to be negative, then the different is even larger (changing both renders the same result due to squaring)

Example 2 with numbers below 0 and 1:

  - 0.2 + 0.5 = 0.7, average = 0.35, squared average 0.1225
  - Summing the squares: `0.04 + 0.25 = 0.29` and dividing by N (2 in this case): `0.145`
  - Difference: `0.145 - 0.1225 = 0.0225`

**Comment by pblenessy** [comment]
Hello,

Thanks for spending time with my patch and describing your thinking.
Having spent a bit more time reading up on SD, I tend to agree with your thinking. Although the examples are a bit short on numbers, considering that the mean is calculated over a period of 20, the theory supports your thinking.

Still the problem remains.
Please consider the below comma separated values, where the 1st column is the input data containing only positive values. Calculations take into account the period length of 20.

As you can see on row 40, the result of (meansq-sqmean) becomes negative, which then triggers an error.

Now, here we have a problem, since the values of meansq and sqmean are exactly the same and the subtraction should hence result in 0.

`data,sqdata,meansq,mean,sqmean,(meansq-sqmean)
0.00527003,2.77732E-05,,,,
0.00527004,2.77733E-05,,,,
0.00526325,2.77018E-05,,,,
0.00525112,2.75743E-05,,,,
0.00525111,2.75742E-05,,,,
0.00525162,2.75795E-05,,,,
0.00527,2.77729E-05,,,,
0.00527,2.77729E-05,,,,
0.00527,2.77729E-05,,,,
0.00527,2.77729E-05,,,,
0.00527,2.77729E-05,,,,
0.00525185,2.75819E-05,,,,
0.00530699,2.81641E-05,,,,
0.00530698,2.8164E-05,,,,
0.00530699,2.81641E-05,,,,
0.005307,2.81642E-05,,,,
0.005307,2.81642E-05,,,,
0.0053072,2.81664E-05,,,,
0.005307,2.81642E-05,,,,
0.0053072,2.81664E-05,2.7887E-05,0.005280769,2.78865E-05,5.0427E-10
0.005307,2.81642E-05,2.79066E-05,0.005282618,2.7906E-05,5.2949E-10
0.005307,2.81642E-05,2.79261E-05,0.005284466,2.79256E-05,5.4789E-10
0.005307,2.81642E-05,2.79492E-05,0.005286653,2.79487E-05,5.4599E-10
0.005307,2.81642E-05,2.79787E-05,0.005289447,2.79782E-05,4.95754E-10
0.005307,2.81642E-05,2.80082E-05,0.005292242,2.80078E-05,4.29864E-10
0.005307,2.81642E-05,2.80375E-05,0.005295011,2.80371E-05,3.50582E-10
0.005307,2.81642E-05,2.80571E-05,0.005296861,2.80567E-05,3.23071E-10
0.005307,2.81642E-05,2.80766E-05,0.005298711,2.80763E-05,2.88714E-10
0.005307,2.81642E-05,2.80962E-05,0.005300561,2.80959E-05,2.47513E-10
0.005307,2.81642E-05,2.81158E-05,0.005302411,2.81156E-05,1.99467E-10
0.005307,2.81642E-05,2.81353E-05,0.005304261,2.81352E-05,1.44575E-10
0.005307,2.81642E-05,2.81644E-05,0.005307018,2.81644E-05,3.70597E-15
0.005307,2.81642E-05,2.81644E-05,0.005307019,2.81644E-05,3.68273E-15
0.005307,2.81642E-05,2.81645E-05,0.00530702,2.81645E-05,3.62473E-15
0.005307,2.81642E-05,2.81645E-05,0.00530702,2.81645E-05,3.59997E-15
0.005307,2.81642E-05,2.81645E-05,0.00530702,2.81645E-05,3.59997E-15
0.005307,2.81642E-05,2.81645E-05,0.00530702,2.81645E-05,3.59997E-15
0.005307,2.81642E-05,2.81644E-05,0.00530701,2.81644E-05,1.89997E-15
0.005307,2.81642E-05,2.81644E-05,0.00530701,2.81644E-05,1.89997E-15
0.005307,2.81642E-05,2.81642E-05,0.005307,2.81642E-05,-3.04932E-20
0.005307,2.81642E-05,2.81642E-05,0.005307,2.81642E-05,-3.04932E-20
0.00525915,2.76587E-05,2.8139E-05,0.005304608,2.81389E-05,1.08757E-10
0.00530697,2.81639E-05,2.8139E-05,0.005304606,2.81388E-05,1.0875E-10`

**Comment by pblenessy** [comment]
Some more digging led me to this description of floating point representation error 
https://docs.python.org/2/tutorial/floatingpoint.html#representation-error

It seams very much like this is the root cause of the problem I am experiencing.
What do you think?

**Comment by mementum** [comment]
Indeed it seems that floating point accuracy plays a role here.

The best option to add the `abs`, to keep the original behavior is to add a parameter to the indicator. This is the same that was done with the Stochastic, for people that had extreme conditions and hit the undetermined division.

Something like:

```python
class StandardDeviation(Indicator):
    params = (('period', 20), ('movav', MovAv.Simple), ('_abs', False),)

    def __init__(self):
        ...
        if self.p._abs:
            self.lines.stddev = pow(abs(meansq - sqmean), 0.5)
        else:
            self.lines.stddev = pow(meansq - sqmean, 0.5)
```

You simply pass `_abs=True` when creating the indicator if you suspect your values are going to hit the precision limits.

**Comment by pblenessy** [comment]
I have updated to patch now according to your comments.
Changed `_abs` to `safepow` instead, think it is a bit more descriptive. Hope it works for you as well.

**Comment by mementum** [comment]
In release 1.9.8.99

**Pull request merged**
